from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


# ── Request Models ─────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message:    str            = Field(...,           min_length=1, description="User's natural language message")
    session_id: Optional[str]  = Field("default",    description="Session ID for conversation continuity")
    student_id: Optional[str]  = Field("S001",       description="Student ID — defaults to S001 mock student")

    class Config:
        json_schema_extra = {
            "example": {
                "message":    "Show my attendance for this month.",
                "session_id": "session_001",
                "student_id": "S001"
            }
        }


class ClearSessionRequest(BaseModel):
    session_id: str = Field(..., description="Session ID to clear")


# ── Response Models ────────────────────────────────────────────────────────────

class ExecutionPlan(BaseModel):
    tool:             str
    args:             Dict[str, Any] = {}


class ChatResponse(BaseModel):
    intent:         str                     = Field(...,  description="Detected intent")
    response:       str                     = Field(...,  description="Natural language response")
    status:         str                     = Field(...,  description="Good / Average / Poor / Pending / Clear / Info / Error")
    session_id:     str                     = Field(...,  description="Session ID used")
    tools_called:   List[str]               = Field([],   description="ERP tools that were executed")
    plan:           List[Dict[str, Any]]    = Field([],   description="Execution plan generated by planner")
    reasoning:      Optional[str]           = Field(None, description="Agent reasoning explanation")
    execution_time: float                   = Field(...,  description="Total processing time in seconds")
    timestamp:      str                     = Field(...,  description="Response timestamp")
    data:           Optional[Dict[str, Any]]= Field(None, description="Raw tool results")

    class Config:
        json_schema_extra = {
            "example": {
                "intent":         "Attendance",
                "response":       "Your attendance for June 2026 is 88.0%. You were absent 4 days.",
                "status":         "Average",
                "session_id":     "session_001",
                "tools_called":   ["get_attendance"],
                "plan":           [{"tool": "get_attendance", "args": {"month": "2026-06"}}],
                "reasoning":      "User asked about attendance | Plan: Fetch June attendance",
                "execution_time": 1.243,
                "timestamp":      "2026-06-29 14:30:00",
                "data":           {}
            }
        }


class HistoryMessage(BaseModel):
    role:       str
    message:    str
    intent:     Optional[str] = None
    timestamp:  str


class HistoryResponse(BaseModel):
    session_id:    str
    total_messages: int
    messages:      List[HistoryMessage]


class SessionsResponse(BaseModel):
    total_sessions: int
    sessions:       List[Dict[str, Any]]


class ClearSessionResponse(BaseModel):
    success:    bool
    session_id: str
    message:    str


class ErrorResponse(BaseModel):
    error:      str
    detail:     Optional[str] = None
    status_code: int